services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  node:
    privileged: true
    image: node:latest
    user: "node"
    # trun on interactive mode
    stdin_open: true
    tty: true
    # the command directive will using working_dir to start
    #working_dir: /home/node/app/hello-framework
    working_dir: /home/node/app
    #environment:
    #  - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "5173"
    ports: # use if it is necessary to expose the container to the host machine
      - "5173:5173"
    # the --host will allow remote connections
    # we need execute npm install first
    command: bash -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173" 
    # use bash to get startd,
    #command: "bash"
